name: update_issues_list
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 0/1 * * *"

jobs:
  update_issues_list:
    runs-on: ubuntu-latest

    steps:
      - name: actions-checkout
        uses: actions/checkout@main #采用main分支下的

      - name: Setup Node.js
        uses: actions/setup-node@v2 #安装node.js
        with:
          node-version: "14"

      - name: Install Dependency
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          npm install
          npm install axios         
          node ./scripts/update_issues_list.js
          git add .
          git commit -m "action update"
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}