name: update_issues_list
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0/1 * * *"

jobs:
  update_issues_list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main #采用main分支下的
      - name: Setup Node.js
        uses: actions/setup-node@v2 #安装node.js
        with:
          node-version: "14"

      - name: Install Dependency
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          npm install
          npm install axios         
          # content=$(node ./scripts/update_issues_list.js)
          git add README.md
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "test" >> README.md
          git commit -m "Update issues list"
          git push

